"""init migration 3

Revision ID: 07f009930a0f
Revises: b7cdedfb08a2
Create Date: 2024-10-27 13:50:42.751316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f009930a0f'
down_revision: Union[str, None] = 'b7cdedfb08a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('updated_at', sa.DATETIME(), server_default=sa.text("(TIMEZONE('utc', now()))"), nullable=False))
    # ### end Alembic commands ###
