"""init migration 2

Revision ID: b7cdedfb08a2
Revises: c7d6ffd42fd8
Create Date: 2024-10-27 13:49:17.215529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7cdedfb08a2'
down_revision: Union[str, None] = 'c7d6ffd42fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(TIMEZONE('utc', now()))"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated_at')
    # ### end Alembic commands ###
